// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADXB6SUw-AINKe4Pd3GsyOqe6W0Rfwcu0',
    appId: '1:530879895661:web:7328b1ecf2da41077fc764',
    messagingSenderId: '530879895661',
    projectId: 'arya-manga',
    authDomain: 'arya-manga.firebaseapp.com',
    storageBucket: 'arya-manga.appspot.com',
    measurementId: 'G-F52XVDNNXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2_2XVnDvabwARqhF5gkzitqbHQkDzmC8',
    appId: '1:530879895661:android:7e37e20da98f351e7fc764',
    messagingSenderId: '530879895661',
    projectId: 'arya-manga',
    storageBucket: 'arya-manga.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-EEBjJ-K2Y75nEJZtvZy98NMk4J5_Cv8',
    appId: '1:530879895661:ios:387affda7f3e73eb7fc764',
    messagingSenderId: '530879895661',
    projectId: 'arya-manga',
    storageBucket: 'arya-manga.appspot.com',
    iosClientId: '530879895661-4p789dc63ebkc6g8n3fia77t82t1mivh.apps.googleusercontent.com',
    iosBundleId: 'com.example.aryaManga',
  );
}
